# Generated by Django 4.1.2 on 2022-10-05 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2000)),
                ('shorten_url', models.CharField(max_length=7)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('last_used_on', models.DateField(default=datetime.date.today)),
                ('total_hits', models.IntegerField(default=0)),
            ],
        ),
    ]
